parameters:
#    localuri_local.example.class: Localuri\LocalBundle\Example

services:
#    localuri_local.example:
#        class: %localuri_local.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
