parameters:
    dictionary_service.class:      Localuri\DictionaryBundle\Entity\DictionaryService

services:
    dictionary_service:
        class:        "%dictionary_service.class%"
        arguments: [@doctrine.orm.entity_manager]
