lcl_user:
    resource: "@LocaluriUserBundle/Resources/config/routing/user.yml"
    prefix:   /

#admin part
lcl_user_admin:
    resource: "@LocaluriUserBundle/Resources/config/routing/user_admin.yml"
    prefix:   /admin