localuri_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: LocaluriUserBundle:Default:index }

#admin part
#Main routes
localuri_user_admin:
    resource: "@LocaluriUserBundle/Resources/config/routing_admin.yml"
    prefix:   /admin