#Main routes
localuri_user_myAccount:
    pattern:  /
    defaults: { _controller: LocaluriUserBundle:User:myAccount }
    requirements:
        _method:  GET

#admin part
localuri_user_admin:
    resource: "@LocaluriUserBundle/Resources/config/routing_admin.yml"
    prefix:   /admin