parameters:
    my_user_provider.class: Localuri\UserBundle\Security\Core\User\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id, github: github_id}]
    user_type:
        class: Localuri\UserBundle\Form\UserType
        arguments: [@dictionary_service]
    localuri_user.password_resetting:
        class: Localuri\UserBundle\EventListener\PasswordResettingListener
        arguments: [@router,@security.context, @fos_user.user_manager]
        tags:
            - { name: kernel.event_subscriber }