parameters:
    my_user_provider.class: Localuri\UserBundle\Security\Core\User\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id, github: github_id}]
    user_type:
        class: Localuri\UserBundle\Form\UserType
        arguments: [@dictionary_service]
#    localuri_user.example:
#        class: %localuri_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
