<?php

namespace Localuri\DictionaryBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DictionaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictionaryRepository extends EntityRepository
{
    /**
     * Returns an array (pair key=>value) of records with type=$type from the dictionary table
     *
     * @param null $type
     * @return array
     */
    public function getQBChoices($type = null){
        $q = $this->createQueryBuilder('d')
            ->select('d');
        if(null === $type)
            $q->where('d.type is null');
        else
            $q->where('d.type = :type')
                ->setParameter('type',$type);

        $q->orderBy('d.value');

        return $q;
    }

    /**
     * Returns a dictionary record based on $id
     * @param $id
     * @return mixed
     */
    public function getDictionary($id){
        $q = $this->createQueryBuilder('d')
            ->select('d')
            ->where('d.id = :id')
            ->setParameter('id',$id);

        return $q->fetchOne();
    }

}