lcl_user_admin:
    pattern:  /
    defaults: { _controller: "LocaluriUserBundle:User:index" }

lcl_user_admin_show:
    pattern:  /{id}/show
    defaults: { _controller: "LocaluriUserBundle:User:show" }

lcl_user_admin_new:
    pattern:  /new
    defaults: { _controller: "LocaluriUserBundle:User:new" }

lcl_user_admin_create:
    pattern:  /create
    defaults: { _controller: "LocaluriUserBundle:User:create" }
    requirements: { _method: post }

lcl_user_admin_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "LocaluriUserBundle:User:edit" }

lcl_user_admin_update:
    pattern:  /{id}/update
    defaults: { _controller: "LocaluriUserBundle:User:update" }
    requirements: { _method: post }

lcl_user_admin_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "LocaluriUserBundle:User:delete" }
    requirements: { _method: post }
