parameters:
#    localuri_address.example.class: Localuri\AddressBundle\Example

services:
#    localuri_address.example:
#        class: %localuri_address.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
